class Product {
  final String title;
  final String image;
  final double price;
  final String category;
  final String description;
  final String size;
  int quantity;

  Product({
    required this.title,
    required this.image,
    required this.price,
    required this.category,
    required this.description,
    required this.size,
    required this.quantity,
  });
}

final List<Product> products = [
  Product(
    title: "Man",
    image: "images/Collections/p1.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p2.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p3.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p4.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p5.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p6.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p7.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p8.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p9.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p10.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p1.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p2.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p3.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p4.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Man",
    image: "images/Collections/p5.jpg",
    price: 20,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
];
