class Product {
  final String title;
  final String image;
  final double price;
  final String category;
  final String description;
  final String size;
  int quantity;

  Product({
    required this.title,
    required this.image,
    required this.price,
    required this.category,
    required this.description,
    required this.size,
    required this.quantity,
  });
}

final List<Product> products = [
  Product(
    title: "Linen Button Shirt",
    image: "images/Collections/p1.jpg",
    price: 24.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Wool Crew Sweater",
    image: "images/Collections/p2.jpg",
    price: 39.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Classic Henley Top",
    image: "images/Collections/p3.jpg",
    price: 22.50,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Wide-Leg Black Jeans",
    image: "images/Collections/p4.jpg",
    price: 45.00,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Relaxed Cotton Tee",
    image: "images/Collections/p5.jpg",
    price: 14.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Oversized Hoodie",
    image: "images/Collections/p6.jpg",
    price: 34.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Pleated Chino Pants",
    image: "images/Collections/p7.jpg",
    price: 32.00,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Denim Overshirt",
    image: "images/Collections/p8.jpg",
    price: 42.50,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Striped Polo Shirt",
    image: "images/Collections/p9.jpg",
    price: 27.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Light Wash Straight Jeans",
    image: "images/Collections/p10.jpg",
    price: 44.00,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Linen Button Shirt",
    image: "images/Collections/p1.jpg",
    price: 24.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Wool Crew Sweater",
    image: "images/Collections/p2.jpg",
    price: 39.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Classic Henley Top",
    image: "images/Collections/p3.jpg",
    price: 22.50,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Wide-Leg Black Jeans",
    image: "images/Collections/p4.jpg",
    price: 45.00,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
  Product(
    title: "Relaxed Cotton Tee",
    image: "images/Collections/p5.jpg",
    price: 14.99,
    category: "category",
    description: "description",
    size: "L",
    quantity: 1,
  ),
];
